Lady Lollipop/Models/Pagination.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lady_Lollipop.Models
{
    public class Pagination
    {
       

        public int TotalItems { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int TotalPages { get; set; }
        public int StartPage { get; set; }
        public int EndPage { get; set; }

        public Pagination()
        {
        }

        public Pagination(int totalItems,int page,int pageSize)
        {
            int totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            int currentPage = page;
            int startPage = currentPage - 5;
            int endPage = currentPage + 4;

            if (startPage <= 0)
            {
                endPage -= (startPage - 1);
                startPage = 1;
            }
            if (endPage > totalPages)
            {
                endPage = totalPages;
                if (endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }
            TotalItems = totalItems;
            TotalPages = totalPages;
            PageSize = pageSize;
            CurrentPage = currentPage;
            PageSize = pageSize;
            StartPage = startPage;
            EndPage = endPage;

        }



    }
}

Lady Lollipop/Controllers/CakesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lady_Lollipop.Data;
using Lady_Lollipop.Models;
using Lady_Lollipop.Data.Services;

namespace Lady_Lollipop.Controllers
{
    public class CakesController : Controller
    {
        private readonly ICakesService _service;
        private readonly ApplicationDbContext _context;

        public CakesController(ICakesService service, ApplicationDbContext context)
        {
            _service = service;
            _context = context;
        }

        // GET: Cakes
        public async Task<IActionResult> Index(string sortOrder, int page=1)
        {
            ViewBag.PriceSortParam = String.IsNullOrEmpty(sortOrder) ? "price_desc" : "";
            ViewBag.StockSortParam = String.IsNullOrEmpty(sortOrder) ? "stock_desc" : "stock_asc";
            var cakes = await _context.Cakes.ToListAsync();
            cakes = cakes.OrderByDescending(s => s.Price).ToList<Cake>();

            switch (sortOrder)
            {
                case "price_desc":
                    cakes = cakes.OrderBy(s => s.Price).ToList<Cake>();
                    break;
                case "stock_desc":
                    cakes = cakes.OrderByDescending(s => s.Stock).ToList<Cake>();
                    break;
                case "stock_asc":
                    cakes = cakes.OrderBy(s => s.Stock).ToList<Cake>();
                    break;
                default:
                    //sweets =sweets.OrderBy(s => s.Price).ToList<Sweet>();
                    break;
            }

            const int pageSize = 8;
            if (page < 1)
            {
                page = 1;
            }
            int resCount = cakes.Count();
            var pager = new Pagination(resCount, page, pageSize);
            int resSkip = (page - 1) * pageSize;
            var data = cakes.Skip(resSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pagination = pager;


            return View(data);
        }
        public async Task<IActionResult> Filter(string searchString)
        {
            var allCakes = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allCakes.Where(n => n.Name.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }

            return View("Index", allCakes);
        }

        // GET: Cakes/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var cake = await _service.GetCakeByIdAsync(id);

            if (cake == null)
            {
                return NotFound();
            }

            return View(cake);
        }

        // GET: Cakes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cakes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Picture,Name,Price,Stock,Description,Ingridients")] Cake cake)
        {
            if (!ModelState.IsValid)
            {
                return View(cake);
            }
            await _service.AddAsync(cake);
            return RedirectToAction(nameof(Index));
        }

        // GET: Cakes/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var cake = await _service.GetByIdAsync(id);
            if (cake == null) return NotFound();
            return View(cake);
        }

        // POST: Cakes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Picture,Name,Price,Stock,Description,Ingridients")] Cake cake)
        {
            if (id != cake.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(id, cake);

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CakeExists(cake.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cake);
        }

        // GET: Cakes/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var cake = await _service.GetByIdAsync(id);
            if (cake == null) return NotFound();
            return View(cake);
        }

        // POST: Cakes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cake = await _service.GetByIdAsync(id);
            if (cake == null) return NotFound();
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private bool CakeExists(int id)
        {
            return _service.Any(id);
        }
    }
}

Lady Lollipop/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lady_Lollipop.Data;
using Lady_Lollipop.Models;
using Lady_Lollipop.Data.Services;
using Lady_Lollipop.Data.Cart;
using Lady_Lollipop.Data.ViewModel;
using System.Security.Claims;

namespace Lady_Lollipop.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ISweetsService _sweetService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(ISweetsService sweetService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _sweetService = sweetService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders =await _ordersService.GetOrderByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }


        // GET: Orders
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddToShoppingCart(int id)
        {
            var item = await _sweetService.GetSweetByIdAsync(id);
            if(item != null)
            {
                _shoppingCart.AddItemToCart(item);
                
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> RemoveFromShoppingCart(int id)
        {
            var item = await _sweetService.GetSweetByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.RemoveFromCart(item);

            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");

        }
    }
}

Lady Lollipop/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;


    <head>
        <link rel="stylesheet" href="~/css/Mashup.css" />
    </head>

    <div class="header-div">
        @if (!User.Identity.IsAuthenticated)
        {
            <a class="profile-link profile-login" asp-controller="Account" asp-action="Login"><p>Login</p></a>
            <a class="profile-link" asp-controller="Account" asp-action="Register"><p>Register</p></a>
        }
        else
        {
            <div style="padding-right: 20px; padding-left: 10px;" class="dropdown">
                <button class="btn dropdown-toggle " style="display:flex;" type="button" id="profile-btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <p class="p-fullName"> @UserManager.GetUserName(User) </p>
                    <img src="~/Images/profile_icon.png" />
                </button>
                <ul class="dropdown-menu" aria-labelledby="profile-btn">
                    <li>
                        <a class="dropdown-item" asp-controller="Orders" asp-action="Index"> Orders</a>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>
                            <a class="dropdown-item" asp-controller="Account" asp-action="Users"> Users</a>
                        </li>
                    }

                    <li>
                        <form asp-controller="Account" asp-action="Logout">
                            <button class="dropdown-item">Log Out</button>
                        </form>
                    </li>
                </ul>
            </div>
            @await Component.InvokeAsync("ShoppingCartSummary")
        }
    </div>

Lady Lollipop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lady Lollipop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/HomeStyle.css" />

</head>
<body>
    <header>
        <div class="header-layout">
            <div>
                <form asp-action="Filter">
                    <input name="searchString" type="text" class="search-bar" placeholder="Search" />
                    <button type="submit" style="display:contents;"><img class="search-icon" src="~/Images/search.PNG" /></button>
                </form>
            </div>
            <a asp-controller="home" asp-action="index"><img class="logo" src="~/Images/logo.PNG" /></a>

            <partial name="_Identity.cshtml" />

        </div>
        <div class="out-nav-div">
            <div class="nav-div">
                <a class="p-navbar" asp-controller="home" asp-action="index">Home</a>
                <a class="p-navbar" asp-controller="sweets" asp-action="index">Sweets</a>
                <a class="p-navbar" asp-controller="Cakes" asp-action="Index">Cakes</a>
                <a class="p-navbar" asp-controller="drinks" asp-action="index">Drinks</a>
            </div>
        </div>
    </header>
    <div class="container-fluid" style="height: 650px; display: table; background-color: #f9d4e478; ">
        @RenderBody()
    </div>
    <footer class="layout-footer">
        <div>
            <p class="footer-p">Copyright© 2021| Lady Lollipop</p>
            <div class="div-footer">
                <a class="a-footer" href="#">Privacy Policy</a>
                <a class="a-footer" href="#">Terms of Use</a>
                <a class="a-footer" href="#">About us</a>
                <a class="a-footer" href="#">Contact us</a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Lady Lollipop/Views/Shared/_Pagination.cshtml
@model Lady_Lollipop.Models.Pagination

<head>
    <link rel="stylesheet" href="~/css/Pagination.css" />
</head>


<div class="container">
    @if (Model.TotalPages > 0)
    {
    <ul class="pagination justify-content-center">
        @if (Model.CurrentPage > 1)
        {
            <li class="page-item">
                <a class="page-link" asp-action="Index" asp-route-page="1">First</a>
            </li>
            <li class="page-item">
                <a class="page-link" asp-action="Index" asp-route-page="@(Model.CurrentPage-1)">Previous</a>
            </li>
        }


        @for (var pg = Model.StartPage; pg <= Model.EndPage; pg++)
        {
            <li class="page-item @(pg==Model.CurrentPage ? "active":"" )">
                <a class="page-link" asp-action="Index" asp-route-page="@pg"> @pg</a>
            </li>
        }
        @if (Model.CurrentPage < Model.TotalPages)
        {
            <li class="page-item">
                <a class="page-link" asp-action="Index" asp-route-page="@(Model.CurrentPage+1)">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link" asp-action="Index" asp-route-page="@(Model.TotalPages)">Last</a>
            </li>
        }
    </ul>
    }

</div>