Lady Lollipop/Models/Drink.cs
using Lady_Lollipop.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Lady_Lollipop.Models
{
    public class Drink:IEntityBase
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Picture is Required")]
        public string Picture { get; set; }
        [Required(ErrorMessage = "Name is Required")]
        public string Name { get; set; }
        public double Price { get; set; }
        public int Stock { get; set; }
        public string Description { get; set; }
        public string Ingridients { get; set; }
    }
}

Lady Lollipop/Controllers/DrinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lady_Lollipop.Data;
using Lady_Lollipop.Models;
using Lady_Lollipop.Data.Services;

namespace Lady_Lollipop.Controllers
{
    public class DrinksController : Controller
    {
        private readonly IDrinksService _service;
        private readonly ApplicationDbContext _context;

        public DrinksController(IDrinksService service, ApplicationDbContext context)
        {
            _service = service;
            _context = context;
        }

        // GET: Drinks
        public async Task<IActionResult> Index(string sortOrder, int page=1)
        {
            ViewBag.PriceSortParam = String.IsNullOrEmpty(sortOrder) ? "price_desc" : "";
            ViewBag.StockSortParam = String.IsNullOrEmpty(sortOrder) ? "stock_desc" : "stock_asc";
            var drinks = await _context.Drinks.ToListAsync();
            drinks = drinks.OrderByDescending(s => s.Price).ToList<Drink>();

            switch (sortOrder)
            {
                case "price_desc":
                    drinks = drinks.OrderBy(s => s.Price).ToList<Drink>();
                    break;
                case "stock_desc":
                    drinks = drinks.OrderByDescending(s => s.Stock).ToList<Drink>();
                    break;
                case "stock_asc":
                    drinks = drinks.OrderBy(s => s.Stock).ToList<Drink>();
                    break;
                default:
                    //sweets =sweets.OrderBy(s => s.Price).ToList<Sweet>();
                    break;
            }

            const int pageSize = 8;
            if (page < 1)
            {
                page = 1;
            }
            int resCount = drinks.Count();
            var pager = new Pagination(resCount, page, pageSize);
            int resSkip = (page - 1) * pageSize;
            var data = drinks.Skip(resSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pagination = pager;


            return View(data);
        }
        public async Task<IActionResult> Filter(string searchString)
        {
            var allDrinks = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allDrinks.Where(n => n.Name.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }

            return View("Index", allDrinks);
        }

        // GET: Drinks/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var drink = await _service.GetDrinkByIdAsync(id);

            if (drink == null)
            {
                return NotFound();
            }

            return View(drink);
        }

        // GET: Drinks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Drinks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Picture,Name,Price,Stock,Description,Ingridients")] Drink drink)
        {
            if (!ModelState.IsValid)
            {
                return View(drink);
            }
            await _service.AddAsync(drink);
            return RedirectToAction(nameof(Index));
        }

        // GET: Drinks/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var drink = await _service.GetByIdAsync(id);
            if (drink == null) return NotFound();
            return View(drink);
        }

        // POST: Drinks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Picture,Name,Price,Stock,Description,Ingridients")] Drink drink)
        {

            if (id != drink.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(id, drink);

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DrinkExists(drink.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(drink);
        }

        // GET: Drinks/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            var drink = await _service.GetByIdAsync(id);
            if (drink == null) return NotFound();
            return View(drink);
        }

        // POST: Drinks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var drink = await _service.GetByIdAsync(id);
            if (drink == null) return NotFound();
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private bool DrinkExists(int id)
        {
            return _service.Any(id);
        }
    }
}

Lady Lollipop/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lady_Lollipop.Data;
using Lady_Lollipop.Models;
using Lady_Lollipop.Data.Services;
using Lady_Lollipop.Data.Cart;
using Lady_Lollipop.Data.ViewModel;
using System.Security.Claims;

namespace Lady_Lollipop.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ISweetsService _sweetService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(ISweetsService sweetService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _sweetService = sweetService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders =await _ordersService.GetOrderByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }


        // GET: Orders
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddToShoppingCart(int id)
        {
            var item = await _sweetService.GetSweetByIdAsync(id);
            if(item != null)
            {
                _shoppingCart.AddItemToCart(item);
                
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> RemoveFromShoppingCart(int id)
        {
            var item = await _sweetService.GetSweetByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.RemoveFromCart(item);

            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");

        }
    }
}

Lady Lollipop/Views/Drinks/Create.cshtml
@model Lady_Lollipop.Models.Drink

@{
    ViewData["Title"] = "Add a Drink";
}

<head>
    <link rel="stylesheet" href="~/css/drinks.css" />
</head>
<h1 class="h1-create-edit">Add a new drink</h1>

<hr style="border: 1px solid #fd4b4b9e;" />
<div>
    <div>
        <form asp-action="Create" class="form-create-edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group text-center">
                <img class="img-create-edit" id="PicturePreview" />
            </div>
            <div class="form-group div-create-edit">
                <label asp-for="Picture" class="control-label label-create-edit"></label>
                <input class="input-create-edit form-control" asp-for="Picture" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group div-create-edit">
                <label asp-for="Name" class="control-label label-create-edit"></label>
                <input class="input-create-edit form-control" asp-for="Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group div-create-edit">
                <label asp-for="Price" class="control-label label-create-edit"></label>
                <input class="input-create-edit form-control" asp-for="Price" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group div-create-edit">
                <label asp-for="Stock" class="control-label label-create-edit"></label>
                <input class="input-create-edit form-control" asp-for="Stock" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group div-create-edit">
                <label asp-for="Description" class="control-label label-create-edit"></label>
                <textarea class="input-create-edit form-control" asp-for="Description"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group div-create-edit">
                <label asp-for="Ingridients" class="control-label label-create-edit"></label>
                <textarea class="input-create-edit form-control" asp-for="Ingridients"></textarea>
                <span asp-validation-for="Ingridients" class="text-danger"></span>
            </div>
            <div class="form-group" style="display: flex; justify-content: space-between; margin-left: 15px;">
                <a class="cancel-create-edit" asp-action="index"> Cancel</a>
                <input class="submit-create-edit" type="submit" value="Create" />
            </div>
        </form>

    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
    $(document).ready(function () {
        var output = document.getElementById('PicturePreview');
        output.src = $('#Picture').val();
    })
    $('#Picture').on("change", function () {
        var output = document.getElementById('PicturePreview');
        output.src = $(this).val();
    })
    </script>
}

Lady Lollipop/Views/Drinks/Delete.cshtml
@model Lady_Lollipop.Models.Drink

@{
    ViewData["Title"] = "Delete a drink";
}
<head>
    <link rel="stylesheet" href="~/css/drinks.css" />
</head>
<h1 class="h1-create-edit">Delete a drink</h1>
<hr style="border: 1px solid #fd4b4b9e;" />
<div>

    <div class="form-group text-center">
        <img class="img-delete" id="PicturePreview" />
    </div>
    <div>
        <div class="form-group ">
            <input class="input-create form-control" style="display:none;" asp-for="Picture" />
        </div>
        <div class="form-group div-create">
            <p class="name-delete">
                @Html.DisplayFor(model => model.Name)
            </p>
        </div>
    </div>


    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <p class="p-delete">Are you sure u want to delete it?</p>
        <div class="form-group delete-form-div">
            <a class="cancel-delete" asp-action="index">Cancel</a>
            <input type="submit" value="Delete" class="submit-delete" />
        </div>


    </form>
</div>


@section Scripts {
    <script>
            $(document).ready(function () {
                var output = document.getElementById('PicturePreview');
                output.src = $('#Picture').val();
            })
    </script>
}

Lady Lollipop/Views/Drinks/Details.cshtml
@model Lady_Lollipop.Models.Drink

@{
    ViewData["Title"] = "Details";
}


<head>
    <link rel="stylesheet" href="~/css/drinks.css" />
</head>

<div class="main-div-details">

    <div class="form-group text-center">
        <img class="img-details" id="PicturePreview" />
    </div>
    <div style="padding-top:13px;">
        <div class="form-group ">
            <input class="input-create form-control" style="display:none;" asp-for="Picture" />
        </div>
        <div class="form-group div-create">
            <p class="name-details">
                @Html.DisplayFor(model => model.Name)
            </p>
        </div>
        <div class="form-group div-create">
            <p class="price-details">$@Html.DisplayFor(model => model.Price)</p>
        </div>
        <div class="form-group div-create">
            <p class="description-details">
                @Html.DisplayFor(model => model.Description)
            </p>
        </div>

        <div class="form-group div-create">
            <p class="stock-details">
                @Html.DisplayFor(model => model.Stock) in Stock
            </p>

        </div>


    </div>
    @if (User.Identity.IsAuthenticated)
    {
        <a class="a-cart-details-drinks" asp-controller="Orders" asp-action="AddToShoppingCart" asp-route-id="@Model.Id"><p class="cart-button-details">Add To Cart</p></a>
    }
    else
    {

        <button disabled class="cart-button-details-disabled">Add To Cart</button>

    }

</div>


@section Scripts {
    <script>
        $(document).ready(function () {
            var output = document.getElementById('PicturePreview');
            output.src = $('#Picture').val();
        })
    </script>
}

Lady Lollipop/Views/Drinks/Edit.cshtml
@model Lady_Lollipop.Models.Drink

@{
    ViewData["Title"] = "Edit a Drink";
}

<head>
    <link rel="stylesheet" href="~/css/drinks.css" />
</head>
<h1 class="h1-create-edit">Edit a drink</h1>

<hr style="border: 1px solid #fd4b4b9e;" />
<div>
    <div>
        <form asp-action="Edit" class="form-create-edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group text-center">
                <img class="img-create-edit" id="PicturePreview" />
            </div>
            <div class="form-group div-create-edit">
                <label asp-for="Picture" class="control-label label-create-edit"></label>
                <input asp-for="Picture" class="input-create-edit form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group div-create-edit">
                <label asp-for="Name" class="control-label label-create-edit"></label>
                <input asp-for="Name" class="input-create-edit form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group div-create-edit">
                <label asp-for="Price" class="control-label label-create-edit"></label>
                <input asp-for="Price" class="input-create-edit form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group div-create-edit">
                <label asp-for="Stock" class="control-label label-create-edit"></label>
                <input asp-for="Stock" class="input-create-edit form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group div-create-edit">
                <label asp-for="Description" class="control-label label-create-edit"></label>
                <textarea asp-for="Description" class="input-create-edit form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group div-create-edit">
                <label asp-for="Ingridients" class="control-label label-create-edit"></label>
                <textarea asp-for="Ingridients" class="input-create-edit form-control"></textarea>
                <span asp-validation-for="Ingridients" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:flex;justify-content:space-between;margin-left:15px;">
                <a class="cancel-create-edit" asp-action="index"> Cancel</a>
                <input type="submit" value="Update" class="submit-create-edit" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(document).ready(function () {
            var output = document.getElementById('PicturePreview');
            output.src = $('#Picture').val();
        })
        $('#Picture').on("change", function () {
            var output = document.getElementById('PicturePreview');
            output.src = $(this).val();
        })
    </script>
}

Lady Lollipop/Views/Drinks/Index.cshtml
@model IEnumerable<Lady_Lollipop.Models.Drink>

@{
    ViewData["Title"] = "List of Drinks";

    Pagination pagination = new Pagination();
    int pageNo = 0;
    if (ViewBag.Pagination != null)
    {
        pagination = ViewBag.Pagination;
        pageNo = pagination.CurrentPage;
    }


}
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p style="text-align:center;">
        <a class="create-button" asp-action="Create">Add <i style="position:relative;top:1px;" class="bi bi-plus-circle-dotted"></i></a>
    </p>
}
<head>
    <link rel="stylesheet" href="~/css/drinks.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
</head>


<div>
    <h1 class="title"> Drinks</h1>
    <div class="dropdown dropleft" style="position: relative; float: right; bottom: 55px;">
        <button class="drinks-filter btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Filters
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" asp-action="Index" asp-route-sortOrder="@ViewBag.PriceSortParam">Price</a>
            <a class="dropdown-item" asp-action="Index" asp-route-sortOrder="@ViewBag.StockSortParam">Stock</a>
        </div>
    </div>
    <ul class="row-div">
        @foreach (var item in Model)
        {
            <li class="main-inside-div">
                <div>
                    <a asp-controller="Drinks" asp-action="Details" asp-route-id="@item.Id"><img class="img-drink" src="@item.Picture" /></a>
                </div>
                <div>
                    <p class="name-p"><a asp-controller="Drinks" class="name-p" asp-action="Details" asp-route-id="@item.Id">@item.Name</a></p>
                    <p class="price-p" step="0.01">$@item.Price</p>
                    <p class="stock-p">@item.Stock in stock</p>
                </div>
                @if (item.Stock >= 1 && User.Identity.IsAuthenticated)
                {

                    <a class="cart-button-enabled" asp-controller="Orders" asp-action="AddToShoppingCart" asp-route-id="@item.Id"><p>Add To Cart</p></a>


                }
                else
                {
                    <div>
                        <button disabled class="cart-button">Add To Cart</button>
                    </div>

                }
                <div class="index-button-div">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <a class="edit-delete-drinks" asp-controller="Drinks" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-fill text-light edit-pencil"></i></a>
                        <a class="edit-delete-drinks" asp-controller="Drinks" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash text-light delete-can"></i></a>
                    }
                </div>
            </li>
        }
    </ul>
</div>
<partial name="_Pagination" model="@pagination" />